## Artificial Neural Network : Churn_Modelling.csv

### Part 1 : Data Processing

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# importing the data base 
dataset=pd.read_csv("datasets/Churn_Modelling.csv")
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values
print("x : \n",x)
print()
print("y : ",y)

x : 
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

y :  [1 0 1 ... 1 1 0]


In [5]:
#Encoding categorical data

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
# ?LabelEncoder
# ?OneHotEncoder

In [6]:
from sklearn.compose import ColumnTransformer 
# ?ColumnTransformer


In [7]:
ct=ColumnTransformer([("Geography",OneHotEncoder(),[1])],remainder='passthrough')
x=ct.fit_transform(x)
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
labelencoder_X2 = LabelEncoder()
x[:, 4] = labelencoder_X2.fit_transform(x[:, 4])
x = x[: , 1:]
print (x)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [9]:
x=np.array(x,dtype=float)
# ?np.array
print(x)

[[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [10]:
#spliting the data set into the training set and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [11]:
print("X_train : \n",X_train)
print("y_train : \n",y_train)
print("X_test : \n",X_test)
print("y_test : \n",y_test)

X_train : 
 [[0.0000000e+00 1.0000000e+00 6.6700000e+02 ... 1.0000000e+00
  0.0000000e+00 1.6383064e+05]
 [1.0000000e+00 0.0000000e+00 4.2700000e+02 ... 1.0000000e+00
  1.0000000e+00 5.7098000e+04]
 [0.0000000e+00 0.0000000e+00 5.3500000e+02 ... 1.0000000e+00
  0.0000000e+00 1.8563076e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.3800000e+02 ... 1.0000000e+00
  0.0000000e+00 1.8142987e+05]
 [0.0000000e+00 1.0000000e+00 5.9000000e+02 ... 1.0000000e+00
  1.0000000e+00 1.4875016e+05]
 [1.0000000e+00 0.0000000e+00 6.2300000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1885526e+05]]
y_train : 
 [0 0 0 ... 0 0 1]
X_test : 
 [[1.0000000e+00 0.0000000e+00 5.9700000e+02 ... 1.0000000e+00
  1.0000000e+00 1.9285267e+05]
 [0.0000000e+00 0.0000000e+00 5.2300000e+02 ... 1.0000000e+00
  0.0000000e+00 1.2870210e+05]
 [0.0000000e+00 1.0000000e+00 7.0600000e+02 ... 1.0000000e+00
  1.0000000e+00 7.5732250e+04]
 ...
 [0.0000000e+00 1.0000000e+00 5.7800000e+02 ... 1.0000000e+00
  0.0000000e+00 1.4153319e+05]
 [1.00

In [12]:
#feature scaling 

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print("X_train : \n",X_train)
print("X_test : \n",X_test)

X_train : 
 [[-0.5698444   1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [-0.5698444  -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-0.5698444   1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [ 1.75486502 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]]
X_test : 
 [[ 1.75486502 -0.57369368 -0.55204276 ...  0.64259497  0.9687384
   1.61085707]
 [-0.5698444  -0.57369368 -1.31490297 ...  0.64259497 -1.03227043
   0.49587037]
 [-0.5698444   1.74309049  0.57162971 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-0.5698444   1.74309049 -0.74791227 ...  0.64259497 -1.03227043
   0.71888467]
 [ 1.75486502 -0.57369368 -0.00566991 ...  0.64259497  0.9687384
  -1.54507805]
 [ 1.75486502 -0.57369368 -0.79945688 ...  0.64259497 -1.03227043
   1.61255917]

### Part 2 : Build ANN

In [13]:
pip install keras


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [14]:
pip install tensorflow


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

2024-02-21 06:22:21.258831: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-21 06:22:21.297355: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-21 06:22:21.297401: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-21 06:22:21.298504: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-21 06:22:21.304286: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-21 06:22:21.305348: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [16]:
# ?Sequential  
# ?Dense       

In [17]:
# initialising the ANN
classifier=Sequential()

#Adding the input layer and the first hidden layer 
# classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(units= 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [18]:
#Adding the second hidden layer 
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [19]:
# Adding the output layer 
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [20]:
# Printing the summary of the classifier 
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
#complining the Ann
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [22]:
#Fitting the ANN
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100


800/800 [==============================] - 1s 1ms/step - loss: 0.4896 - accuracy: 0.7955
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4282 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4219 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4179 - accuracy: 0.8121
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4155 - accuracy: 0.8270
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4136 - accuracy: 0.8313
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4122 - accuracy: 0.8325
Epoch 8/100
800/800 [==============================] - 1s 992us/step - loss: 0.4105 - accuracy: 0.8330
Epoch 9/100
800/800 [==============================] - 1s 992us/step - loss: 0.4095 - accuracy: 0.8342
Epoch 10/100
800/800 [==============================] - 1s 991us/step - loss: 0.4084 - accuracy: 0.

### Part 3 : Making the predictions and evalauting the model (CM)

In [23]:
#Predicting the The Test Results
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

63/63 [==============================] - 0s 702us/step


In [24]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)


[[1541   54]
 [ 249  156]]


In [25]:
# ?confusion_matrix