In [1]:
import numpy as np
# from matplotlib import pyplot as plt

1st array (1d, complex)

In [2]:
array = np.array([1,2,3,4,5], dtype=complex)
array


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [3]:
array.dtype


dtype('complex128')

In [4]:
print(array)
type(array)



[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


numpy.ndarray

In [5]:
array.itemsize

16

In [6]:
array.size

5

In [7]:
len(array)

5

In [8]:
array.shape

(5,)

2nd array (2d, int)

In [9]:
a = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
a.ndim

2

In [11]:
a.itemsize

4

In [12]:
a.dtype

dtype('int32')

In [13]:
a.size #tells total number of elements in array

9

In [14]:
len(a) 

3

In [15]:
a.shape

(3, 3)

3rd array

In [16]:
rect = np.array([[1,2,3,4,5,6],[5,6,7,8,9,10]], order='F')

In [17]:
rect

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9, 10]])

In [18]:
rect.size

12

In [19]:
len(rect)

2

In [20]:
rect.shape

(2, 6)

In [21]:
rect_transpose = (rect.reshape(6,2))

In [22]:
rect_transpose


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
len(rect_transpose) #tells number of rows

6

In [24]:
rect_transpose.size

12

In [25]:
print(rect)
print("total sum of elements : ",rect.sum())
print("sum of row elements : ",sum(rect_transpose))
print("sum of col elements : ",sum(rect))
print("sum of sum row : ", sum(sum(rect_transpose)))
print("sum of sum col : ", sum(sum(rect)))

print("max of col sum : ", max(sum(rect)))
print("max of row sum : ", max(sum(rect_transpose)))

[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]]
total sum of elements :  66
sum of row elements :  [30 36]
sum of col elements :  [ 6  8 10 12 14 16]
sum of sum row :  66
sum of sum col :  66
max of col sum :  16
max of row sum :  36


In [26]:
rect

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9, 10]])

In [34]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
